export const VERIFICATION_STATES = {
  LOADING: 'LOADING',
  CHECKBOX_CARD: 'CHECKBOX_CARD',
  INITIALIZING: 'INITIALIZING',
  ANALYZING: 'ANALYZING',
  HUMAN_DETECTED: 'HUMAN_DETECTED',
  CAPTCHA_PROMPT: 'CAPTCHA_PROMPT',
  REVERSED_CAPTCHA: 'REVERSED_CAPTCHA',
  CAPTCHA_RESULT: 'CAPTCHA_RESULT',
  OPENCV_INITIALIZING: 'OPENCV_INITIALIZING',
  OPENCV_SCANNING: 'OPENCV_SCANNING',
  ROBOT_VERIFIED: 'ROBOT_VERIFIED',
  ACCESS_GRANTED: 'ACCESS_GRANTED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  RESETTING: 'RESETTING'
};

export const TRANSITION_EVENTS = {
  BOOT_COMPLETE: 'BOOT_COMPLETE',
  CHECKBOX_CHECKED: 'CHECKBOX_CHECKED',
  START_VERIFICATION: 'START_VERIFICATION',
  HUMAN_SCORE_100: 'HUMAN_SCORE_100',
  PROCEED_TO_CAPTCHA: 'PROCEED_TO_CAPTCHA',
  CAPTCHA_SUBMIT_CORRECT: 'CAPTCHA_SUBMIT_CORRECT',
  CAPTCHA_SUBMIT_INCORRECT: 'CAPTCHA_SUBMIT_INCORRECT',
  PROCEED_TO_OPENCV: 'PROCEED_TO_OPENCV',
  PROCEED_TO_PROTECTED_SITE: 'PROCEED_TO_PROTECTED_SITE',
  OPENCV_READY: 'OPENCV_READY',
  OPENCV_VERIFIED_ROBOT: 'OPENCV_VERIFIED_ROBOT',
  OPENCV_VERIFIED_HUMAN: 'OPENCV_VERIFIED_HUMAN',
  RESET: 'RESET'
};

const TRANSITION_TABLE = {
  [VERIFICATION_STATES.LOADING]: {
    [TRANSITION_EVENTS.BOOT_COMPLETE]: VERIFICATION_STATES.CHECKBOX_CARD
  },
  [VERIFICATION_STATES.CHECKBOX_CARD]: {
    [TRANSITION_EVENTS.CHECKBOX_CHECKED]: VERIFICATION_STATES.INITIALIZING
  },
  [VERIFICATION_STATES.INITIALIZING]: {
    [TRANSITION_EVENTS.START_VERIFICATION]: VERIFICATION_STATES.ANALYZING
  },
  [VERIFICATION_STATES.ANALYZING]: {
    // ANALYZING (Task 01) -> HUMAN_DETECTED
    [TRANSITION_EVENTS.HUMAN_SCORE_100]: VERIFICATION_STATES.HUMAN_DETECTED
  },
  [VERIFICATION_STATES.HUMAN_DETECTED]: {
    // HUMAN_DETECTED -> CAPTCHA_PROMPT / REVERSED_CAPTCHA (Strictly prohibited from going straight to OPENCV_*)
    [TRANSITION_EVENTS.PROCEED_TO_CAPTCHA]: VERIFICATION_STATES.REVERSED_CAPTCHA
  },
  [VERIFICATION_STATES.CAPTCHA_PROMPT]: {
    [TRANSITION_EVENTS.PROCEED_TO_CAPTCHA]: VERIFICATION_STATES.REVERSED_CAPTCHA
  },
  [VERIFICATION_STATES.REVERSED_CAPTCHA]: {
    [TRANSITION_EVENTS.CAPTCHA_SUBMIT_CORRECT]: VERIFICATION_STATES.CAPTCHA_RESULT,
    [TRANSITION_EVENTS.CAPTCHA_SUBMIT_INCORRECT]: VERIFICATION_STATES.OPENCV_INITIALIZING
  },
  [VERIFICATION_STATES.CAPTCHA_RESULT]: {
    [TRANSITION_EVENTS.PROCEED_TO_OPENCV]: VERIFICATION_STATES.OPENCV_INITIALIZING
  },
  [VERIFICATION_STATES.OPENCV_INITIALIZING]: {
    [TRANSITION_EVENTS.OPENCV_READY]: VERIFICATION_STATES.OPENCV_SCANNING
  },
  [VERIFICATION_STATES.OPENCV_SCANNING]: {
    [TRANSITION_EVENTS.OPENCV_VERIFIED_ROBOT]: VERIFICATION_STATES.ROBOT_VERIFIED,
    [TRANSITION_EVENTS.OPENCV_VERIFIED_HUMAN]: VERIFICATION_STATES.ACCESS_DENIED
  },
  [VERIFICATION_STATES.ROBOT_VERIFIED]: {
    [TRANSITION_EVENTS.START_VERIFICATION]: VERIFICATION_STATES.ACCESS_GRANTED,
    [TRANSITION_EVENTS.PROCEED_TO_PROTECTED_SITE]: VERIFICATION_STATES.ACCESS_GRANTED
  }
};

/**
 * Single exported transition function for App.jsx
 * @param {string} currentState 
 * @param {string} event 
 * @returns {string} nextState
 */
export function getNextState(currentState, event) {
  if (event === TRANSITION_EVENTS.RESET) {
    return VERIFICATION_STATES.CHECKBOX_CARD;
  }
  const stateTransitions = TRANSITION_TABLE[currentState];
  if (stateTransitions && stateTransitions[event]) {
    return stateTransitions[event];
  }
  return currentState;
}
